neighbors = {
    'AK': [],
    'AL': ['MS', 'TN', 'GA', 'FL'],
    'AR': ['MO', 'TN', 'MS', 'LA', 'TX', 'OK'],
    'AZ': ['CA', 'NV', 'UT', 'CO', 'NM'],
    'CA': ['OR', 'NV', 'AZ'],
    'CO': ['WY', 'NE', 'KS', 'OK', 'NM', 'AZ', 'UT'],
    'CT': ['NY', 'MA', 'RI'],
    'DC': ['MD', 'VA'],
    'DE': ['MD', 'PA', 'NJ'],
    'FL': ['AL', 'GA'],
    'GA': ['FL', 'AL', 'TN', 'NC', 'SC'],
    'HI': [],
    'IA': ['MN', 'WI', 'IL', 'MO', 'NE', 'SD'],
    'ID': ['MT', 'WY', 'UT', 'NV', 'OR', 'WA'],
    'IL': ['WI', 'IA', 'MO', 'KY', 'IN'],
    'IN': ['MI', 'IL', 'KY', 'OH'],
    'KS': ['NE', 'MO', 'OK', 'CO'],
    'KY': ['IL', 'IN', 'OH', 'WV', 'VA', 'TN', 'MO'],
    'LA': ['TX', 'AR', 'MS'],
    'MA': ['RI', 'CT', 'NY', 'VT', 'NH'],
    'MD': ['VA', 'WV', 'PA', 'DE', 'DC'],
    'ME': ['NH'],
    'MI': ['WI', 'IN', 'OH'],
    'MN': ['ND', 'SD', 'IA', 'WI'],
    'MO': ['IA', 'IL', 'KY', 'TN', 'AR', 'OK', 'KS', 'NE'],
    'MS': ['LA', 'AR', 'TN', 'AL'],
    'MT': ['ID', 'WY', 'SD', 'ND'],
    'NC': ['VA', 'TN', 'GA', 'SC'],
    'ND': ['MT', 'SD', 'MN'],
    'NE': ['SD', 'IA', 'MO', 'KS', 'CO', 'WY'],
    'NH': ['VT', 'ME', 'MA'],
    'NJ': ['PA', 'DE', 'NY'],
    'NM': ['AZ', 'UT', 'CO', 'OK', 'TX'],
    'NV': ['OR', 'ID', 'UT', 'AZ', 'CA'],
    'NY': ['NJ', 'PA', 'VT', 'MA', 'CT'],
    'OH': ['MI', 'IN', 'KY', 'WV', 'PA'],
    'OK': ['CO', 'KS', 'MO', 'AR', 'TX', 'NM'],
    'OR': ['WA', 'ID', 'NV', 'CA'],
    'PA': ['NY', 'NJ', 'DE', 'MD', 'WV', 'OH'],
    'RI': ['CT', 'MA'],
    'SC': ['GA', 'NC'],
    'SD': ['ND', 'MN', 'IA', 'NE', 'WY', 'MT'],
    'TN': ['KY', 'VA', 'NC', 'GA', 'AL', 'MS', 'AR', 'MO'],
    'TX': ['NM', 'OK', 'AR', 'LA'],
    'UT': ['ID', 'WY', 'CO', 'NM', 'AZ', 'NV'],
    'VA': ['MD', 'DC', 'NC', 'TN', 'KY', 'WV'],
    'VT': ['NY', 'NH', 'MA'],
    'WA': ['ID', 'OR'],
    'WI': ['MI', 'IL', 'IA', 'MN'],
    'WV': ['OH', 'PA', 'MD', 'VA', 'KY'],
    'WY': ['MT', 'SD', 'NE', 'CO', 'UT', 'ID']
}
